### ISSUE TITLE
Unsupported Grant Type Error.

### ISSUE THREAD

**Issue by wcosmas** [JubaerHossain/zoom-laravel#11]
I have been getting the error below when i try to create meeting. Any idea on how to debug it
message":"Error creating meeting: Client error: `POST https:\/\/zoom.us\/oauth\/token` resulted in a `400 Bad Request` response:\n{\"reason\":\"unsupported grant type\",\"error\":\"unsupported_grant_type\"}\n

**Comment by JubaerHossain** [comment]
you need to re-check to token. please follow docs carefully

**Comment by wcosmas** [comment]
Thanks @JubaerHossain. I was able to fix it
