### ISSUE TITLE
Is possible to hide join link or disable it?

### ISSUE THREAD

**Issue by D0nVitalio** [JubaerHossain/zoom-laravel#18]
Hi, here it is:
![image](https://github.com/user-attachments/assets/ba4a8653-9ba4-4b69-9fee-c439629f24ce)

Is it possible hide or disable it?

**Comment by JubaerHossain** [comment]
> Hi, here it is: ![image](https://private-user-images.githubusercontent.com/22496972/362868524-ba4a8653-9ba4-4b69-9fee-c439629f24ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5OTEwMTYsIm5iZiI6MTcyNDk5MDcxNiwicGF0aCI6Ii8yMjQ5Njk3Mi8zNjI4Njg1MjQtYmE0YTg2NTMtOWJhNC00YjY5LTlmZWUtYzQzOTYyOWYyNGNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDA0MDUxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1YTgyYWZkNWJmZjhhNDJiYjAwNWIxZWU1NzRlNWU3MGVlMDFjY2I5MzExZjBmOTU3NWFhN2YyYjg0YmQzMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qC6rlyS-AcQf18s1_n6e6Fp-RgPXcFYh42wUv7J2-7A)
> 
> Is it possible hide or disable it?

No, this link is generated by the Zoom SDK.

**Comment by D0nVitalio** [comment]
> No, this link is generated by the Zoom SDK.

On Zoom forum they found how to solve it
[](https://devforum.zoom.us/t/how-to-hide-the-meeting-password-and-the-invite-url-in-zoom-meeting-sdk/93071/2?u=vit)

add the parameter “meetingInfo” on “ZoomMtg.init({” and disable “pwd”, “invite”
```
ZoomMtg.init({
 ...
      meetingInfo: [
        'topic',       // Meeting Title
        'mn',          // Meeting ID
        'host',        // Host name
        // 'pwd',         // Passcode
        // 'telPwd',      // Numeric Passcode
        // 'invite',      // Invite link
        'participant', // Participant ID
        'dc',          //
        'enctype',     // Encryption
        'report'
      ],
```

But I'm not sure where to put it.. In `Zoom::createMeeting` or where I create JWT token? Have any idea?

**Comment by D0nVitalio** [comment]
Found it in 
`function beginJoin(signature) {`
but can't make it  hide link.
