### ISSUE TITLE
Invalid client_id or client_secret

### ISSUE THREAD

**Issue by vishal-livebix** [JubaerHossain/zoom-laravel#3]
@JubaerHossain  
i have added all details of key ,appid and secret.
zoom has deprecated jwt so i have added  server to server oauth app details

Client error: `POST https://zoom.us/oauth/token` resulted in a `400 Bad Request` response: {"reason":"Invalid client_id or client_secret","error":"invalid_client"}

**Comment by JubaerHossain** [comment]
Please seethe documents properly

**Comment by vishal-livebix** [comment]
i have followed all step properly then still not wroking
